name: run-CI-CD-pipeline-docker-container

on:
  pull_request:
    branches: ["main"]

jobs:
  ci-cd-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and run Docker compose
        run: |
          docker-compose up -d
